### PR TITLE
Network Operator watches for NicClusterPolicy with predefined name

### LINKED ISSUE #17: [Change Request] Enforce only one instance of nicclusterpolicy CR
we should programmatically prevent the processing of more than one instance of `nicclusterpolicy` CR.

e.g on first processing create a secret if pass then continue , if fail with object exists, update CR status with error

### PR DESCRIPTION
**Pull request by Mmduh-483**
Network Operator watches only for NicPolicy with name "nic-cluster-policy" to prevent polices overlapping

Signed-off-by: Mamduh Alassi <mamduhala@mellanox.com>

Fixes #17

### CODE REVIEW

File: pkg/controller/nicclusterpolicy/nicclusterpolicy_controller.go [hunk 1]
```diff
@@ -124,6 +132,19 @@ func (r *ReconcileNicClusterPolicy) Reconcile(request reconcile.Request) (reconc
 		return reconcile.Result{}, err
 	}
 
+	if !isSupportedInstance {
+		instance.Status.State = mellanoxv1alpha1.StateIgnore
```
Comment (adrianchiris) [inline pkg/controller/nicclusterpolicy/nicclusterpolicy_controller.go:136]: can you put all the logic in a helper method : `handleUnsupportedInstance()` ?
also the Logging from L#113-119

File: pkg/controller/nicclusterpolicy/nicclusterpolicy_controller.go [hunk 2]
```diff
@@ -109,6 +110,13 @@ func (r *ReconcileNicClusterPolicy) Reconcile(request reconcile.Request) (reconc
 	reqLogger := log.WithValues("Request.Namespace", request.Namespace, "Request.Name", request.Name)
 	reqLogger.V(consts.LogLevelInfo).Info("Reconciling NicClusterPolicy")
 
+	isSupportedInstance := request.Name == consts.NicPolicyResourceName
+	if !isSupportedInstance {
+		reqLogger.V(consts.LogLevelInfo).Info("unsupported NicPolicy instance", "instance name:", request.Name)
```
Comment (adrianchiris) [inline pkg/controller/nicclusterpolicy/nicclusterpolicy_controller.go:115]: > nicPolicy

please use the full name throughout the commit : nicClusterPolicy

File: pkg/consts/consts.go [hunk 3]
```diff
@@ -30,4 +30,5 @@ const (
 
 const (
 	NetworkOperatorResourceNamespace = "mlnx-network-operator-resources"
+	NicPolicyResourceName            = "cluster-nic-policy"
```
Comment (adrianchiris) [inline pkg/consts/consts.go:33]: `NicClusterPolicyResourceName = "nic-cluster-policy"`

File: README.md [hunk 4]
```diff
@@ -61,6 +61,8 @@ The Operator Acts on the following CRDs:
 ### NICClusterPolicy CRD
 CRD that defines a Cluster state for Mellanox Network devices.
 
+>__NOTE__: Operator watch only for NicClusterPolicy with predefined name "cluster-nic-policy", instances with different names will be ignored.
```
Comment (adrianchiris) [inline README.md:64]: i prefer : `nic-cluster-policy` like the CRD name, no need to swap the words :)

**Review by adrianchiris — CHANGES_REQUESTED** [review]
missing updates to the helm deployment templates found under `deployment` directory

**Comment by adrianchiris** [comment]
@Mmduh-483 please adjust commit message to reflect the correct name

File: README.md [hunk 5]
```diff
@@ -61,6 +61,8 @@ The Operator Acts on the following CRDs:
 ### NICClusterPolicy CRD
 CRD that defines a Cluster state for Mellanox Network devices.
 
+>__NOTE__: Operator watch only for NicClusterPolicy with predefined name "nic-cluster-policy", instances with different names will be ignored.
```
Comment (adrianchiris) [inline README.md:64]: suggested reword.

>__NOTE__: The operator will act on a NicClusterPolicy instance with a predefined name "nic-cluster-policy", instances with different names will be ignored.

File: pkg/controller/nicclusterpolicy/nicclusterpolicy_controller.go [hunk 6]
```diff
@@ -124,6 +128,11 @@ func (r *ReconcileNicClusterPolicy) Reconcile(request reconcile.Request) (reconc
 		return reconcile.Result{}, err
 	}
 
+	if !isSupportedInstance {
```
Comment (adrianchiris) [inline pkg/controller/nicclusterpolicy/nicclusterpolicy_controller.go:131]: can you move L114 here ? it would be clearer as this is the only place that you use it.
better yet, just 

```
// Support only a single instance of NicClusterPolicy
if request.Name != consts.NicClusterPolicyResource name {
....
}
``

File: pkg/controller/nicclusterpolicy/nicclusterpolicy_controller.go [hunk 7]
```diff
@@ -187,3 +196,21 @@ NextResult:
 		log.V(consts.LogLevelError).Info("Failed to update CR status", "error:", err)
 	}
 }
+
+func (r *ReconcileNicClusterPolicy) handleUnsupportedInstance(instance *mellanoxv1alpha1.NicClusterPolicy,
+	request reconcile.Request, reqLogger logr.Logger) error {
+	reqLogger.V(consts.LogLevelInfo).Info("unsupported NicClusterPolicy instance", "instance name:", request.Name)
```
Comment (adrianchiris) [inline pkg/controller/nicclusterpolicy/nicclusterpolicy_controller.go:202]: it should be LogLevelWarninng IMO.

**Review by adrianchiris — COMMENTED** [review]
need to adjust commit message to reflect the new CR name
and i believe you missed updating the CR template in helm deployment

**Review by adrianchiris — APPROVED** [review]
